### ISSUE TITLE
[BUG] GIF在首页上的展示存在问题

### ISSUE THREAD

**Issue by Kira-Pgr** [WeepingDogel/tinygallery#2]
在首页gif缩略图无法展示
![image](https://user-images.githubusercontent.com/36188023/211456745-5cb55ba0-c642-4fa0-9b6e-d6fc58e027e3.png)
修复建议:
*  首页展示GIF截图
*  换一种压缩GIF方法

**Comment by WeepingDogel** [comment]
我的方案是禁止上传GIF（bushi

**Comment by WeepingDogel** [comment]
```py
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'bmp'}
```

已经解决了 不允许直接上传 GIF 文件，未来会实现要求用户逐帧上传的功能，然后临时生成动图.

**Comment by Kira-Pgr** [comment]
好诶~
